modLoader="javafml"
loaderVersion="${loader_version_range}"
license="GPLv3"
issueTrackerURL="https://github.com/TyrellPlayz/BigIndustries/issues" #optional
[[mods]]
modId="big_industries"
version="${mod_version}"
displayName="Big Industries"
#updateJSONURL="https://change.me.example.invalid/updates.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/big-industries"
logoFile="big_industries.png"
credits="Thanks for this example mod goes to Java"
authors="Love, Cheese and small house plants"
description='Adds machines to Minecraft'
[[dependencies.big_industries]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.big_industries]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.big_industries]]
    modId="zlib"
    mandatory=true
    versionRange="[${zlib_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.big_industries]]
    modId="flywheel"
    mandatory=true
    versionRange="[1.18-0.5.0.31,)"
    ordering="NONE"
    side="BOTH"
